title: Early Intervention See Saw 
description: Ups and downs..blah 

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: 
   twitter: eiseesaw
   facebook: 
   email: clairelrowland@gmail.com

google_analytics: ""
