title: Early Intervention See Saw 
description: Ups and downs..blah 

url: "http://www.earlyinterventionseesaw.com" 
baseurl: ""
paginate_path: "blog/page:num/"
permalink: pretty
#permalink: blog/:title/
#relative_permalinks: true

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: 
   twitter: eiseesaw
   facebook: 
   email: 

google_analytics: "UA-64592413-1"

gems:
  - jekyll-sitemap

